baseURL = 'https://visualnerve.caripson.com/'
defaultContentLanguage = 'en'
title = 'Visual Nerve'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term', 'RSS', '404']
[outputs]
home = ['HTML', 'Error']
[outputFormats.Error]
mediaType = 'text/html'
baseName = 'error'
isHTML = true
notAlternative = true
[markup.goldmark.renderer]
unsafe = false
[markup.highlight]
noClasses = false
[params]
environment = 'staging'
googleAnalyticsMeasurementId = ''
