import { supportedCodeFile } from '../catalog';
import type { ProjectIgnoredReason } from './types';

/** Path filters are applied before root stripping as well as after it. */
export function projectPathReason(path: string): ProjectIgnoredReason | undefined {
  const parts = path.toLowerCase().split('/');
  if (parts.some((part) => ['.git', '.hg', '.svn', '.bzr'].includes(part))) return 'vcs';
  if (
    parts.some((part) =>
      ['node_modules', 'vendor', '.venv', 'venv', 'site-packages', 'bower_components'].includes(
        part,
      ),
    )
  )
    return 'dependency';
  if (
    parts.some((part) =>
      [
        'dist',
        'build',
        'target',
        'out',
        'coverage',
        '.next',
        '.nuxt',
        '.cache',
        '__pycache__',
      ].includes(part),
    )
  )
    return 'build';
  const basename = parts.at(-1) ?? '';
  if (
    parts.some((part) => ['.aws', '.ssh', '.gnupg'].includes(part)) ||
    /^(?:\.env(?:\..*)?|\.netrc|\.npmrc|\.pypirc|\.git-credentials|credentials(?:\..*)?|secrets?(?:\..*)?|id_(?:rsa|dsa|ecdsa|ed25519)(?:\.pub)?)$/.test(
      basename,
    ) ||
    /\.(?:pem|key|p12|pfx|keystore)$/.test(basename)
  )
    return 'private';
  if (
    parts.some((part) => ['generated', '.generated', 'autogenerated'].includes(part)) ||
    /(?:\.min\.[^.]+|\.bundle\.[^.]+|\.generated\.[^.]+|\.g\.(?:cs|dart)|\.pb\.(?:go|cc|h)|\.map)$/.test(
      basename,
    ) ||
    [
      'package-lock.json',
      'yarn.lock',
      'pnpm-lock.yaml',
      'cargo.lock',
      'composer.lock',
      'poetry.lock',
    ].includes(basename)
  )
    return 'generated';
  if (path.endsWith('/')) return 'directory';
  if (
    /\.(?:png|jpe?g|gif|webp|svg|ico|pdf|zip|gz|bz2|7z|rar|tar|woff2?|ttf|eot|mp[34]|wav|ogg|webm|mov|exe|dll|so|dylib|class|jar|pyc|bin|dat|db|sqlite|vsdx|docx|xlsx|pptx)$/i.test(
      basename,
    )
  )
    return 'binary';
  // Extensionless scripts are checked by their shebang after decoding.
  if (!supportedCodeFile(path) && basename.includes('.')) return 'unsupported';
  return undefined;
}

export function generatedProjectText(content: string): boolean {
  const heading = content.slice(0, 4_000);
  if (
    /^\s*(?:\/\/|#|\/\*|\*|<!--|;)\s*(?:@generated|<auto-generated|.*\b(?:automatically generated|generated by|do not edit)\b)/im.test(
      heading,
    )
  )
    return true;
  // The analyzer has the same bounded-line contract. Generated one-line bundles are not useful diagrams.
  let lineStart = 0;
  for (let index = 0; index <= content.length; index++) {
    if (index === content.length || content.charCodeAt(index) === 10) {
      if (index - lineStart > 20_000) return true;
      lineStart = index + 1;
    }
  }
  return false;
}

export function privateProjectText(content: string): boolean {
  return /-----BEGIN (?:[A-Z0-9]+ )*PRIVATE KEY-----|^PuTTY-User-Key-File-[23]:/m.test(
    content.slice(0, 4_000),
  );
}
