// Canonical producer templates, not translated runtime state. No private values are stored here.
// The adapter applies only where these engine/settings diagnostics are rendered.
export const presentationMessagePatterns = [
  [
    'presentation.sceneNeedsDetails',
    'Saved scene views require Details. Choose Details or use Auto-fit objects.',
    [],
  ],
  [
    'presentation.sceneTooMany',
    'Storyboard supports at most 1,000 scenes. Select a smaller sequence.',
    [],
  ],
  ['presentation.sceneSelectionRequired', 'Select one or more diagram objects first.', []],
  ['spatial.loadFailedPlayback', 'The 3D view could not be loaded. Return to 2D to play.', []],
  ['spatial.saveBeforeReloadFailed', 'Could not save your changes before reloading. {error}', []],
  ['spatial.cameraInterrupted', 'Camera movement interrupted.', []],
  ['spatial.captureFrameFailed', 'Could not capture the 3D frame.', []],
  ['spatial.renderFacesFailed', 'Could not render the original node faces.', []],
  ['voice.savedBrowser', 'Presentation voice saved for this browser.', []],
  ['voice.modelsCleared', 'Downloaded voice models cleared from this browser.', []],
  ['imports.fileLimitSaved', 'Import file size limit saved for this browser.', []],
  [
    'imports.largeWarning',
    'Only imports up to 50 MB are supported and guaranteed. Larger imports are experimental and may be slow or fail because of browser memory or format limits.',
    [],
  ],
  [
    'imports.sizeSettingInvalid',
    'Import file size limit must be a whole number from 50 MB to 1024 MB (1 GB).',
    [],
  ],
  [
    'imports.byteLimitInvalid',
    'Import byte limit must be a positive whole number no greater than 1 GB.',
    [],
  ],
  ['imports.fileSizeInvalid', '{kind} has an invalid file size.', []],
  [
    'imports.fileTooLarge',
    '{kind} exceeds the configured {megabytes} MB import limit. Increase the import file size limit in Settings or choose a smaller file.',
    ['megabytes'],
  ],
  ['imports.zipLimitSaved', 'ZIP project source-file limit saved for this browser.', []],
  [
    'imports.zipLargeWarning',
    'Only ZIP projects with up to 500 analyzed source files are supported and guaranteed. Larger projects are experimental and may be slow or fail. Raising this limit does not increase byte, archive-entry, line, diagram, symbol, connection or time limits.',
    [],
  ],
  [
    'imports.zipSettingInvalid',
    'ZIP project source-file limit must be a whole number from 500 to 10,000.',
    [],
  ],
  ['presentation.preloadCleared', 'Preload cleared. Prepare this tour again.', []],
  ['presentation.openRequiredDiagram', 'Open the presentation diagram first.', []],
  ['presentation.openDiagramFirst', 'Open a diagram first.', []],
  [
    'presentation.diagramChangedContinue',
    'Diagram changed. Press Play to continue with the updated diagram.',
    [],
  ],
  ['presentation.createSceneBeforePlay', 'Create a storyboard scene before playing.', []],
  ['presentation.numberBeforePlay', 'Number some nodes before playing the diagram.', []],
  ['presentation.objectNoLongerExists', 'This presentation object no longer exists.', []],
  ['presentation.addStepFirst', 'Add a walkthrough node or storyboard scene first.', []],
  ['presentation.seekInvalid', 'Seek index must identify an existing walkthrough step.', []],
  ['presentation.optionsExpected', 'Expected player options.', []],
  [
    'presentation.optionsInvalid',
    'Player options must be audio, subtitles, preload or minimized booleans.',
    [],
  ],
  ['presentation.audioChanged', 'Audio changed. Press Play to continue.', []],
  ['presentation.addStepsBeforePreload', 'Add walkthrough steps before preloading.', []],
  [
    'presentation.preloadStatus',
    'Preload {percent}% · {completed}/{total} steps ready · {detail}',
    ['completed', 'percent', 'total'],
  ],
  ['presentation.preparingFullTour', 'Preparing the entire presentation…', []],
  ['presentation.voiceEngineReady', 'Voice engine ready.', []],
  ['presentation.narrationReady', 'Narration ready.', []],
  ['presentation.noNarrationNeeded', 'No narration needed.', []],
  ['presentation.fullPreloadReady', 'Preload 100% · {total}/{total} steps ready.', ['total']],
  ['presentation.preloadFailed', 'Preload failed: {error}', []],
  ['presentation.diagramChangedPrepare', 'Diagram changed. Prepare this tour again.', []],
  ['presentation.videoAlreadyBusy', 'A video export is already running or being cancelled.', []],
  ['presentation.videoOpenDiagram', 'Open a diagram before exporting video.', []],
  ['presentation.videoCreateScenes', 'Create storyboard scenes first.', []],
  ['presentation.videoNumberNodes', 'Number walkthrough nodes first.', []],
  [
    'presentation.videoDurationLimit',
    'Video export supports up to 30 minutes. Shorten the walkthrough first.',
    [],
  ],
  ['presentation.videoPreparing', 'Preparing local video export…', []],
  ['presentation.videoCanvasRequired', 'Video export needs a canvas renderer.', []],
  [
    'presentation.videoNarrationDurationLimit',
    'The narrated video exceeds 30 minutes. Shorten the descriptions or walkthrough.',
    [],
  ],
  ['presentation.videoObjectMissing', 'A walkthrough object is missing.', []],
  [
    'presentation.videoPreparingStep',
    'Preparing {current} / {total}: {name}',
    ['current', 'total'],
  ],
  [
    'presentation.videoExportingStep',
    'Exporting {current} / {total}: {name}',
    ['current', 'total'],
  ],
  ['presentation.videoFinishing', 'Finishing video file…', []],
  [
    'presentation.videoReady',
    'Video ready. Your browser downloads the file; you can also save it again.',
    [],
  ],
  ['voice.cachedModel', 'Cached {voice}', []],
  ['voice.downloadingModel', 'Downloading {voice}', []],
  [
    'voice.downloadFailedStatus',
    'The voice download failed ({status}). Try again when online.',
    ['status'],
  ],
  ['voice.downloadUnexpectedSize', 'The voice download has an unexpected size.', []],
  ['voice.downloadStreamingUnavailable', 'This browser cannot stream voice downloads.', []],
  ['voice.downloadSizeExceeded', 'The voice download exceeds its expected size.', []],
  ['voice.downloadIncomplete', 'The voice download was incomplete. Try again.', []],
  [
    'voice.downloadIntegrityFailed',
    'Voice integrity verification failed. The download was discarded.',
    [],
  ],
  [
    'voice.configurationInvalid',
    'The voice configuration is invalid. Clear downloaded voices and retry.',
    [],
  ],
  ['voice.emptyAudio', 'The voice engine returned no audio.', []],
  [
    'voice.audioMemoryLimit',
    'Narration audio exceeds the 32 MiB limit. Split it into shorter steps.',
    [],
  ],
  [
    'voice.runtimeLoadFailed',
    'A local voice runtime file could not load ({status}). Reload or check the website deployment.',
    ['status'],
  ],
  ['voice.runtimeFileTooLarge', 'A local voice runtime file exceeds its size limit.', []],
  ['voice.runtimeUnavailable', 'This browser cannot load the local voice runtime.', []],
  ['voice.runtimeEmpty', 'A local voice runtime file is empty.', []],
  ['voice.initializingSession', 'Initializing the local voice session…', []],
  ['voice.initializingPronunciation', 'Initializing the local pronunciation engine…', []],
  ['voice.downloadingPronunciation', 'Downloading the local pronunciation runtime…', []],
  ['voice.noPhonemes', 'The pronunciation engine produced no phonemes.', []],
  ['voice.invalidAudio', 'The voice engine returned invalid audio.', []],
  ['voice.narrationRequired', 'Add narration before preparing audio.', []],
  ['voice.preparingChunk', 'Preparing narration chunk {current} of {total}…', ['current', 'total']],
  ['voice.preparedChunks', 'Prepared {current} of {total} narration chunks.', ['current', 'total']],
  ['voice.waitingForNarration', 'Waiting for the current narration…', []],
  [
    'voice.downloadTimedOut',
    'The voice download stopped receiving data. Check the connection and retry.',
    [],
  ],
  [
    'voice.initializationTimedOut',
    'The local voice initialization stopped responding. Reload and retry.',
    [],
  ],
  [
    'voice.chunkTimedOut',
    'The narration chunk stopped responding. Try a shorter description or reload.',
    [],
  ],
  ['voice.workerTimedOut', 'The local voice worker stopped responding. Reload and retry.', []],
  ['voice.gestureRequired', 'Audio needs a browser gesture. Click Play in the diagram player.', []],
  ['voice.resumeGestureRequired', 'Click Play to resume browser audio.', []],
  ['voice.descriptionRequired', 'Add a description to narrate this object.', []],
  ['voice.characterLimit', 'Narration is limited to 12,000 characters per object.', []],
  ['voice.invalidResponse', 'The voice engine returned an invalid response.', []],
  [
    'voice.couldNotStart',
    'The local voice engine could not start. Please reload or try another voice.',
    [],
  ],
  ['voice.startFailedFallback', 'Could not start the voice engine.', []],
  ['voice.catalogSelectionRequired', 'Select a supported presentation voice from the catalog.', []],
  [
    'voice.fullPreloadCapacity',
    'Full preload exceeds the 1 GiB encrypted temporary audio limit. Shorten this tour.',
    [],
  ],
  [
    'voice.fullPreloadStorageRequired',
    'Full preload needs secure browser storage after 32 MiB. Use HTTPS and allow temporary app storage.',
    [],
  ],
  ['voice.preparedNarrationMissing', 'Prepared narration is missing. Run Preload again.', []],
  [
    'voice.preparedNarrationIntegrityFailed',
    'Prepared narration failed integrity verification. Run Preload again.',
    [],
  ],
  [
    'voice.clipCapacity',
    'A narration clip exceeds the 32 MiB per-object limit. Shorten its description.',
    [],
  ],
  ['voice.clipSizeUnexpected', 'The narration clip has an unexpected size.', []],
  ['voice.clipCleanupFailed', 'Temporary narration cache could not be removed.', []],
  ['voice.workerBusy', 'The voice engine is already preparing audio.', []],
  ['voice.narrationCharacterRange', 'Narration must contain 1 to 12,000 characters.', []],
  [
    'presentation.videoTooLarge',
    'The video exceeds the 256 MB export limit. Shorten the walkthrough and try again.',
    [],
  ],
  [
    'presentation.videoEncodingUnavailable',
    'This browser cannot encode the requested video. Use a browser with WebCodecs AVC/AAC or VP9/Opus encoding.',
    [],
  ],
  [
    'presentation.videoVisibleCardLimit',
    'Video export supports at most {limit} visible cards per frame. Zoom in or filter the diagram.',
    ['limit'],
  ],
  [
    'presentation.videoDiagramChanged',
    'The diagram or its 2D/3D view changed during video export.',
    [],
  ],
  [
    'presentation.videoTextureLimit',
    'The native diagram cards exceeded the video texture memory limit.',
    [],
  ],
  ['presentation.videoHiddenCard', 'The presentation card is hidden or unavailable.', []],
  ['presentation.videoStorageConsentRequired', 'Accept local storage before exporting video.', []],
  ['presentation.videoMcpWriteRequired', 'Video export requires MCP write access.', []],
  ['presentation.videoTabVisibilityRequired', 'Keep the diagram tab visible to export video.', []],
  ['toolbar.layoutDiagramChanged', 'The diagram changed during layout. Run layout again.', []],
  ['shared.saveBeforeReloadFailed', 'Could not save before reloading. {error}', []],
  ['dialogs.imageCanvasUnavailable', 'Could not create an image canvas.', []],
  ['dialogs.exportSelectionRequired', 'Select one or more nodes to export.', []],
  ['dialogs.exportContentRequired', 'Add a node or draw a stroke before exporting an image.', []],
  [
    'dialogs.imageCanvasLimit',
    'This image exceeds the browser canvas limit. Use a smaller resolution, export a selection, or use JSON/Markdown.',
    [],
  ],
  ['dialogs.renderTimeout', 'Graph rendering took too long. Try a smaller selection.', []],
  ['dialogs.renderDecodeFailed', 'Could not decode graph rendering.', []],
  [
    'dialogs.tiledPageLimit',
    'Tiled export would exceed 200 pages. Choose a larger paper size or export a selection.',
    [],
  ],
] as const;
