import { describe, expect, it } from 'vitest';
import { strToU8, Zip, ZipDeflate, zipSync, type Zippable } from 'fflate';
import { loadProjectArchive } from '../src/code/project/archive';
import { decodeProjectArchive } from '../src/code/project/input';

const zip = (files: Record<string, string>, options = {}) =>
  zipSync(
    Object.fromEntries(Object.entries(files).map(([path, content]) => [path, strToU8(content)])),
    options,
  );
function directory(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const end = bytes.length - 22;
  const start = view.getUint32(end + 16, true);
  const entries: number[] = [];
  for (let cursor = start; cursor < end; ) {
    entries.push(cursor);
    cursor +=
      46 +
      view.getUint16(cursor + 28, true) +
      view.getUint16(cursor + 30, true) +
      view.getUint16(cursor + 32, true);
  }
  return { view, end, start, entries };
}
const base64 = (bytes: Uint8Array) => Buffer.from(bytes).toString('base64');

describe('project ZIP integrity and local scanning', () => {
  it('loads code and linked Markdown, preserves relative structure, and strips one common repository wrapper', () => {
    const bytes = zip({
      'example/': '',
      'example/src/main.ts':
        'import { helper } from "./helper"; export function run() { helper(); }',
      'example/src/helper.ts': 'export function helper() {}',
      'example/docs/start.md': '# Start\n[Next](./next.md)',
      'example/docs/next.md': '# Next',
    });
    const progress: unknown[] = [];
    const result = loadProjectArchive(bytes, 'Example', {
      onProgress: (event) => progress.push(event),
    });
    expect(result.name).toBe('Example');
    expect(result.files.map((file) => [file.path, file.language])).toEqual([
      ['src/main.ts', 'typescript'],
      ['src/helper.ts', 'typescript'],
      ['docs/start.md', 'markdown'],
      ['docs/next.md', 'markdown'],
    ]);
    expect(result.expandedBytes).toBe(
      result.files.reduce((total, file) => total + strToU8(file.content).length, 0),
    );
    expect(result.ignored.total).toBe(1);
    expect(result.ignored.reasons.directory).toBe(1);
    expect(progress[0]).toEqual({ stage: 'scan', completed: 0, total: 5 });
    expect(progress.at(-1)).toMatchObject({ stage: 'read', completed: 5, total: 5 });
  });

  it('does not strip separate top-level folders, and strips only one nesting level', () => {
    expect(
      loadProjectArchive(zip({ 'src/app.py': 'pass', 'docs/readme.md': '# App' })).files.map(
        (file) => file.path,
      ),
    ).toEqual(['src/app.py', 'docs/readme.md']);
    expect(
      loadProjectArchive(zip({ 'repo/src/app.py': 'pass', 'repo/src/help.py': 'pass' })).files.map(
        (file) => file.path,
      ),
    ).toEqual(['src/app.py', 'src/help.py']);
  });

  it('identifies extensionless scripts and leaves ambiguous source available for explicit language review', () => {
    const result = loadProjectArchive(
      zip({
        'repo/bin/run': '#!/usr/bin/env python3\nprint("hello")',
        'repo/include/plain.h': 'void run(void);',
        'repo/include/cpp.h': 'namespace engine { class Worker {}; }',
        'repo/query.m': 'let Source = 1 in Source',
      }),
    );
    expect(result.files.map((file) => [file.path, file.language])).toEqual([
      ['bin/run', 'python'],
      ['include/plain.h', undefined],
      ['include/cpp.h', 'cpp'],
      ['query.m', 'powerquery'],
    ]);
  });

  it('counts ignored files by reason and does not return their source contents', () => {
    const files: Zippable = {
      'repo/main.py': strToU8('def run(): pass'),
      'repo/node_modules/dep.js': strToU8('SECRET_DEPENDENCY'),
      'repo/build/bundle.js': strToU8('SECRET_BUILD'),
      'repo/.git/config': strToU8('SECRET_VCS'),
      'repo/.env.production': strToU8('SECRET_ENV'),
      'repo/credentials.json': strToU8('SECRET_CREDENTIAL'),
      'repo/id_ed25519': strToU8('SECRET_PRIVATE_KEY'),
      'repo/generated/model.py': strToU8('SECRET_GENERATED'),
      'repo/ui.min.js': strToU8('SECRET_MINIFIED'),
      'repo/generated_by_tool.py': strToU8(
        '# Generated by a compiler. DO NOT EDIT\nSECRET_GENERATED_TEXT',
      ),
      'repo/photo.png': new Uint8Array([137, 80, 78, 71]),
      'repo/binary.py': new Uint8Array([255, 0, 1]),
      'repo/notes.txt': strToU8('SECRET_UNSUPPORTED'),
      'repo/assets/': new Uint8Array(),
    };
    const result = loadProjectArchive(zipSync(files));
    expect(result.files).toEqual([
      { path: 'main.py', content: 'def run(): pass', language: 'python' },
    ]);
    expect(result.ignored).toEqual({
      total: 13,
      reasons: {
        dependency: 1,
        build: 1,
        vcs: 1,
        private: 3,
        generated: 3,
        binary: 2,
        unsupported: 1,
        directory: 1,
      },
    });
    expect(result.expandedBytes).toBe(
      Object.values(files).reduce((total, value) => total + (value as Uint8Array).length, 0),
    );
    expect(JSON.stringify(result)).not.toContain('SECRET');
  });

  it('filters dependency and private wrapper paths before removing their shared directory', () => {
    expect(() => loadProjectArchive(zip({ 'node_modules/dep.py': 'pass' }))).toThrow(
      'no supported',
    );
    expect(() => loadProjectArchive(zip({ '.ssh/helper.py': 'pass' }))).toThrow('no supported');
  });

  it.each([
    '../main.py',
    '/main.py',
    'C:/main.py',
    'repo/../main.py',
    'repo/./main.py',
    'repo//main.py',
    'repo\\main.py',
    'repo/\u0000.py',
  ])('rejects unsafe archive paths without extracting them: %s', (path) => {
    expect(() => loadProjectArchive(zip({ [path]: 'pass' }))).toThrow('Invalid or unsupported');
  });

  it('rejects duplicate file names and file/directory collisions', () => {
    const bytes = zip({ 'a.py': 'pass', 'b.py': 'pass' });
    const { view, entries } = directory(bytes);
    const secondLocal = view.getUint32(entries[1] + 42, true);
    bytes[secondLocal + 30] = 'a'.charCodeAt(0);
    bytes[entries[1] + 46] = 'a'.charCodeAt(0);
    expect(() => loadProjectArchive(bytes)).toThrow('Invalid or unsupported');
    expect(() =>
      loadProjectArchive(zip({ 'repo/a': '', 'repo/a/': '', 'repo/main.py': 'pass' })),
    ).toThrow('Invalid or unsupported');
  });

  it.each([0xa000, 0x1000, 0x2000, 0x6000])(
    'rejects symlinks and special Unix files (mode %s)',
    (mode) => {
      const bytes = zipSync({
        'main.py': [strToU8('pass'), { os: 3, attrs: (mode | 0o644) << 16 }],
      });
      expect(() => loadProjectArchive(bytes)).toThrow('Invalid or unsupported');
    },
  );

  it('accepts normal Unix file permissions and stored archives', () => {
    const bytes = zipSync({
      'main.py': [strToU8('pass'), { os: 3, attrs: 0o100644 << 16, level: 0 }],
    });
    expect(loadProjectArchive(bytes).files[0].content).toBe('pass');
  });

  it('accepts streamed ZIP data descriptors and rejects malformed descriptor declarations', () => {
    const chunks: Uint8Array[] = [];
    const stream = new Zip((error, data) => {
      if (error) throw error;
      chunks.push(data);
    });
    const source = new ZipDeflate('repo/main.py');
    stream.add(source);
    source.push(strToU8('def run(): pass'), true);
    stream.end();
    const bytes = new Uint8Array(chunks.reduce((total, chunk) => total + chunk.length, 0));
    let offset = 0;
    for (const chunk of chunks) {
      bytes.set(chunk, offset);
      offset += chunk.length;
    }
    expect(loadProjectArchive(bytes).files[0]).toEqual({
      path: 'main.py',
      content: 'def run(): pass',
      language: 'python',
    });
    const { view, entries } = directory(bytes);
    const local = view.getUint32(entries[0] + 42, true);
    const descriptor =
      local +
      30 +
      view.getUint16(local + 26, true) +
      view.getUint16(local + 28, true) +
      view.getUint32(entries[0] + 20, true);
    view.setUint32(descriptor + 8, 1, true);
    expect(() => loadProjectArchive(bytes)).toThrow('Invalid or unsupported');
  });

  it('excludes obvious private key content even when disguised as a source file', () => {
    const result = loadProjectArchive(
      zip({
        'repo/main.py': 'pass',
        'repo/helper.py': '-----BEGIN RSA PRIVATE KEY-----\nSENSITIVE',
      }),
    );
    expect(result.files.map((file) => file.path)).toEqual(['main.py']);
    expect(result.ignored.reasons.private).toBe(1);
  });

  it.each([1, 0x40, 0x2000])('rejects encrypted or masked entries (flag %s)', (flag) => {
    const bytes = zip({ 'main.py': 'pass' });
    const { view, entries } = directory(bytes);
    view.setUint16(6, view.getUint16(6, true) | flag, true);
    view.setUint16(entries[0] + 8, view.getUint16(entries[0] + 8, true) | flag, true);
    expect(() => loadProjectArchive(bytes)).toThrow('Invalid or unsupported');
  });

  it('rejects unsupported compression, split archives, ZIP64 and malformed extra records', () => {
    for (const mutate of [
      ({ view, entries }: ReturnType<typeof directory>) => {
        view.setUint16(8, 99, true);
        view.setUint16(entries[0] + 10, 99, true);
      },
      ({ view, end }: ReturnType<typeof directory>) => view.setUint16(end + 4, 1, true),
      ({ view, entries }: ReturnType<typeof directory>) =>
        view.setUint32(entries[0] + 24, 0xffffffff, true),
      ({ view, entries }: ReturnType<typeof directory>) => view.setUint16(entries[0] + 6, 45, true),
    ]) {
      const bytes = zip({ 'main.py': 'pass' });
      mutate(directory(bytes));
      expect(() => loadProjectArchive(bytes)).toThrow('Invalid or unsupported');
    }
    expect(() =>
      loadProjectArchive(
        zipSync({ 'main.py': [strToU8('pass'), { extra: { 1: new Uint8Array(8) } }] }),
      ),
    ).toThrow('Invalid or unsupported');
    const bytes = zipSync({ 'main.py': [strToU8('pass'), { extra: { 123: new Uint8Array(8) } }] });
    const { view, entries } = directory(bytes);
    const start = entries[0] + 46 + view.getUint16(entries[0] + 28, true);
    view.setUint16(start + 2, 1000, true);
    expect(() => loadProjectArchive(bytes)).toThrow('Invalid or unsupported');
  });

  it('validates both local and central declarations and rejects overlapping ranges', () => {
    const mismatch = zip({ 'main.py': 'pass' });
    new DataView(mismatch.buffer).setUint32(22, 300, true);
    expect(() => loadProjectArchive(mismatch)).toThrow('Invalid or unsupported');
    const overlap = zip({ 'a.py': 'pass', 'b.py': 'pass' }, { level: 0 });
    const { view, entries } = directory(overlap);
    const offset = view.getUint32(entries[1] + 42, true);
    // First file claims the second local header as payload; stored sizes remain consistent.
    const expanded = offset + 10 - (30 + 4);
    view.setUint32(18, expanded, true);
    view.setUint32(22, expanded, true);
    view.setUint32(entries[0] + 20, expanded, true);
    view.setUint32(entries[0] + 24, expanded, true);
    expect(() => loadProjectArchive(overlap)).toThrow('Invalid or unsupported');
  });

  it('checks CRC even for files excluded from analysis', () => {
    const bytes = zip(
      { 'repo/main.py': 'pass', 'repo/node_modules/dep.js': 'ignored' },
      { level: 0 },
    );
    const { view, entries } = directory(bytes);
    const local = view.getUint32(entries[1] + 42, true);
    bytes[local + 30 + view.getUint16(local + 26, true)] ^= 1;
    expect(() => loadProjectArchive(bytes)).toThrow('checksum');
  });

  it('enforces compressed and total declared expanded budgets, including ignored files', () => {
    const bytes = zip({ 'repo/main.py': 'pass', 'repo/node_modules/dep.js': 'x'.repeat(10_000) });
    expect(bytes.length).toBeLessThan(1000);
    expect(() => loadProjectArchive(bytes, 'Too large', { byteLimit: bytes.length - 1 })).toThrow(
      'Project ZIP exceeds',
    );
    expect(() => loadProjectArchive(bytes, 'Too large', { byteLimit: 1000 })).toThrow(
      'Expanded project ZIP exceeds',
    );
  });

  it('stops a forged low-size declaration during bounded inflation instead of accepting a ZIP bomb', () => {
    const bytes = zip({ 'main.py': 'x'.repeat(2_000_000) });
    const { view, entries } = directory(bytes);
    view.setUint32(22, 1, true);
    view.setUint32(entries[0] + 24, 1, true);
    expect(() => loadProjectArchive(bytes, 'Bomb', { byteLimit: 10_000 })).toThrow(
      'exceeds its declared expanded size',
    );
  });

  it('never silently truncates an archive with more than 500 analyzable files', () => {
    const files = Object.fromEntries(
      Array.from({ length: 501 }, (_, index) => [`repo/file${index}.py`, 'pass']),
    );
    expect(() => loadProjectArchive(zip(files))).toThrow('more than 500 analyzable files');
  });

  it('bounds directory-entry count before reading any archive content', () => {
    const bytes = zip({ 'main.py': 'pass' });
    const { view, end } = directory(bytes);
    view.setUint16(end + 8, 10_001, true);
    view.setUint16(end + 10, 10_001, true);
    expect(() => loadProjectArchive(bytes)).toThrow('10,000 entries');
  });

  it('supports cancellation before scanning and from scan/read progress', () => {
    const bytes = zip({ 'repo/main.py': 'pass', 'repo/help.py': 'pass' });
    const aborted = new AbortController();
    aborted.abort();
    expect(() => loadProjectArchive(bytes, 'Cancelled', { signal: aborted.signal })).toThrow(
      /cancelled/,
    );
    for (const stage of ['scan', 'read']) {
      const controller = new AbortController();
      expect(() =>
        loadProjectArchive(bytes, 'Cancelled', {
          signal: controller.signal,
          onProgress: (progress) => {
            if (progress.stage === stage && progress.completed === 1) controller.abort();
          },
        }),
      ).toThrow(/cancelled/);
    }
  });

  it('accepts chunked canonical base64 and rejects malformed, noncanonical, oversized or unsupported input', () => {
    const bytes = zip({ 'main.py': 'pass' });
    expect(decodeProjectArchive({ data: base64(bytes) })).toEqual(bytes);
    expect(decodeProjectArchive({ data: base64(new Uint8Array(20_000)) })).toHaveLength(20_000);
    for (const data of [
      'AA',
      'AA A',
      '====',
      'AA==AA==',
      'AB==',
      'AAB=',
      'éAAA',
      `data:application/zip;base64,${base64(bytes)}`,
    ])
      expect(() => decodeProjectArchive({ data })).toThrow('strict base64');
    expect(() => decodeProjectArchive({ data: base64(bytes) }, 10)).toThrow('import limit');
    expect(() =>
      decodeProjectArchive({ data: base64(bytes), url: 'https://example.com/repo.zip' } as never),
    ).toThrow('optional name');
    expect(() => decodeProjectArchive({ data: base64(bytes), name: ' ' })).toThrow('Project name');
  });

  it('rejects a missing end record, truncation, local name mismatch and corrupt deflate stream', () => {
    const bytes = zip({ 'main.py': 'def main(): return 42' });
    expect(() => loadProjectArchive(bytes.slice(0, -1))).toThrow('Invalid or unsupported');
    expect(() => loadProjectArchive(new Uint8Array(30))).toThrow('Invalid or unsupported');
    const mismatch = bytes.slice();
    mismatch[30] ^= 1;
    expect(() => loadProjectArchive(mismatch)).toThrow('Invalid or unsupported');
    const corrupt = bytes.slice();
    corrupt[30 + 'main.py'.length] = 255;
    expect(() => loadProjectArchive(corrupt)).toThrow('Invalid or unsupported');
  });
});
