import {
  MAX_CAPACITY_CARDS_PER_BANK,
  MAX_ADDITIONAL_CAPACITY_CARDS,
} from '../simulation/capacity-projection';
import { browserApiVersion } from './api-version';
import { parallelLimits } from '../simulation/parallel-topology';
import { ParticleRoute } from '../simulation/particle-route';

export const simulationCapabilities = {
  type: 'process-simulator',
  schemaVersion: 1,
  apiVersion: browserApiVersion,
  engine: 'deterministic-discrete-event',
  timeUnit: 'second',
  currency: 'one configurable currency per model',
  nodeTypes: ['source', 'work', 'router', 'fork', 'join', 'resource', 'outcome'],
  queueDisciplines: ['fifo', 'priority'],
  arrivalDistributions: ['regular', 'poisson'],
  routingModes: ['first-match', 'weighted', 'least-queue', 'available-capacity'],
  speeds: [1, 10, 100, 'max'],
  features: [
    'semantic-crud',
    'hierarchical-processes',
    'parallel-fork-join',
    'process-drilldown',
    'shared-resources',
    'queues',
    'abandonment',
    'complexity',
    'scaling',
    'schedules',
    'improvements',
    'economics',
    'time-to-revenue',
    'scenarios',
    'comparison',
    'payback',
    'seeded-random',
    'replay',
    'headless',
    'bounded-particle-rendering',
    'native-capacity-card-projection',
    'local-persistence',
  ],
  parallel: {
    mode: 'all-mandatory',
    fork: {
      joinNodeId: 'fork.joinNodeId',
      branchEdgeIds: 'fork.branchEdgeIds',
      outgoing: 'all-declared',
      particleTypeFilters: false,
    },
    join: {
      forkNodeId: 'join.forkNodeId',
      correlation: 'business-case-and-fork-group',
      wait: 'all-declared-branches',
    },
    cancellation: 'any-branch-failure-or-abandonment-cancels-entire-case',
    incurredCosts: 'retained-on-cancellation',
    population: 'original-business-cases',
    workTokens: 'independent-queue-resource-consuming-children',
    processingAndWaiting: 'summed-branch-effort',
    timeToRevenue: 'original-creation-to-single-outcome',
    revenue: 'once-after-join-with-composed-branch-multipliers',
    nesting: 'properly-nested-closed-acyclic-regions',
    limits: { ...parallelLimits, liveTokens: 200000 },
    stateField: 'parallel',
    joinMetricsField: 'nodes[].join',
    groupSampling: 'bounded-by-particle-retention',
    mutations: 'atomic-full-model-put-for-pair-and-topology-changes',
  },
  hierarchy: {
    processCollection: 'processes',
    parentField: 'processes[].parentId',
    nodeMembershipField: 'nodes[].processId',
    missingProcesses: 'empty-hierarchy',
    maximumProcesses: 50000,
    maximumDepth: 128,
    execution: 'same-global-engine-and-shared-resource-pools',
    projection: 'read-only-process-cards-and-boundary-edges',
    metrics: {
      scope: 'direct-members-and-all-descendant-processes',
      completed: 'successful-scope-visits-including-exits-and-terminal-outcomes',
      terminalCompleted: 'successful-final-outcomes-inside-scope',
      cycleTime: 'scope-entry-to-exit-or-terminal-outcome',
      ttr: 'scope-entry-to-revenue-producing-terminal-outcome',
      aggregation: 'parent-and-child-totals-overlap-do-not-sum',
      distributions: 'computed-from-scope-observations-never-summed-node-quantiles',
      resourceCostAllocation: 'occupied-units',
      sharedResourceOverhead: 'idle-scaling-and-investment-pool-costs-remain-global',
    },
  },
  visualCapacity: {
    view: '2d',
    representation: 'full-native-cards',
    /** @deprecated Scoped to additional/compact projections; use the explicit editability flags. */
    readOnly: true,
    primaryEditable: true,
    additionalCardsReadOnly: true,
    compactHierarchyReadOnly: true,
    sharedLogicalModel: true,
    persistentUnitIdentity: false,
    occupancy: 'actual-aggregate-busy',
    queueDisplay: 'shared-at-first-card',
    limits: {
      cardsPerBank: MAX_CAPACITY_CARDS_PER_BANK,
      additionalCards: MAX_ADDITIONAL_CAPACITY_CARDS,
    },
    overflow: 'explicit-aggregate-label',
    spatialView: 'logical-model',
  },
  execution: {
    browserRequired: true,
    activeCanvasRequired: false,
    animationRequired: false,
    routeAggregation: {
      exactLabelCharacters: ParticleRoute.labelLimit,
      summaryPrefixCharacters: ParticleRoute.prefixLimit,
      digest: 'ordered-composable-dual-32-bit-with-edge-count',
      completedRouteBuckets: 256,
      overflow: '[other routes]',
      workRevenueAttribution: 'deduplicated-visited-work-nodes',
    },
    limits: {
      activeParticles: 200000,
      semanticEvents: 50000000,
      routeVisits: 10000,
      activeRuns: 4,
      cachedRuns: 60,
    },
    limitBehavior: {
      activeParticlesAndEvents: 'failed run with an explicit message and partial metrics',
      routeVisits: 'failed particle with a semantic event',
      activeRuns:
        '409 rejection before starting another execution or replay worker; paused resident workers and startup reservations count',
    },
  },
  permissions: { inspection: 'read', comparison: 'read', mutationsAndRuns: 'write' },
  transport: { envelopeBytes: 32 * 1024 * 1024, asynchronousRuns: true, eventPageMaximum: 1000 },
  retention: {
    configurable: true,
    completedParticlesBounded: true,
    eventsBounded: true,
    metricsIncludeAllParticles: true,
  },
};
