package main

func addHistorySchemas(schemas object) {
	schemas["HistorySnapshot"] = strictObject([]string{"id", "diagramId", "name", "kind", "createdAt", "graphVersion", "contentId", "sourceIds", "nodes", "edges", "rows"}, object{
		"id": object{"type": "string", "format": "uuid"}, "diagramId": object{"type": "string", "format": "uuid"}, "name": object{"type": "string", "maxLength": 200}, "kind": object{"type": "string", "enum": []string{"named", "source-refresh", "pre-restore"}},
		"createdAt": object{"type": "string", "format": "date-time"}, "graphVersion": object{"type": "integer"}, "contentId": object{"type": "string"}, "sourceIds": stringList(), "nodes": object{"type": "integer"}, "edges": object{"type": "integer"}, "rows": object{"type": "integer"},
	})
	schemas["HistorySnapshot"].(object)["description"] = "Explicit named versions and automatic pre-source-refresh/pre-restore safety checkpoints in local IndexedDB. Up to 50 snapshots per diagram, 1,000 per workspace, 256 MiB archived content total and 32 MiB per structural graph. Immutable source rows are shared across unchanged snapshots. Capacity errors preserve current work and never silently evict named snapshots. This is separate from transient Undo/Redo."
	schemas["HistoryCreate"] = strictObject([]string{"baseVersion", "name"}, object{"baseVersion": object{"type": "integer", "minimum": 1}, "name": object{"type": "string", "minLength": 1, "maxLength": 200}})
	schemas["HistoryRestore"] = strictObject([]string{"baseVersion"}, object{"baseVersion": object{"type": "integer", "minimum": 1}})
	schemas["HistoryRead"] = strictObject([]string{"snapshot", "graph"}, object{"snapshot": ref("HistorySnapshot"), "graph": ref("Graph")})
	schemas["HistoryRestoreResult"] = strictObject([]string{"graph", "safetySnapshot"}, object{"graph": ref("Graph"), "safetySnapshot": ref("HistorySnapshot")})
	schemas["HistoryChange"] = strictObject([]string{"entity", "kind", "id", "label", "fields"}, object{
		"entity": object{"type": "string", "enum": []string{"diagram", "node", "edge", "owner", "source"}}, "kind": object{"type": "string", "enum": []string{"added", "removed", "changed"}}, "id": object{"type": "string"}, "label": object{"type": "string"}, "fields": stringList(),
	})
	schemas["HistoryComparison"] = strictObject([]string{"diagramId", "fromSnapshotId", "toSnapshotId", "currentVersion", "counts", "changes", "totalChanges", "changesTruncated", "affectedNodeIds", "affectedEdgeIds", "affectedTotal", "affectedTruncated", "warnings"}, object{
		"diagramId": object{"type": "string", "format": "uuid"}, "fromSnapshotId": object{"type": "string", "format": "uuid"}, "toSnapshotId": object{"type": "string"}, "currentVersion": object{"type": "integer"},
		"counts":  object{"type": "object", "additionalProperties": object{"type": "object", "properties": object{"added": object{"type": "integer"}, "removed": object{"type": "integer"}, "changed": object{"type": "integer"}}}},
		"changes": object{"type": "array", "items": ref("HistoryChange")}, "totalChanges": object{"type": "integer"}, "changesTruncated": object{"type": "boolean"}, "affectedNodeIds": uuidList(50000), "affectedEdgeIds": stringList(), "affectedTotal": object{"type": "integer"}, "affectedTruncated": object{"type": "boolean"}, "warnings": stringList(),
	})
	schemas["HistoryComparison"].(object)["description"] = "Semantic changes omit revision timestamps and routine viewport movement. Dependency impact follows modeled connections and is not a runtime execution guarantee. Large lists expose truncation flags and complete counts. Restore requires currentVersion as baseVersion and creates a safety checkpoint atomically; stale restore fails with 409. Shared owner profiles remain current so other diagrams are not rewound."
	schemas["HistoryContent"] = strictObject([]string{"id", "diagramId", "digest", "bytes", "graph"}, object{"id": object{"type": "string"}, "diagramId": object{"type": "string", "format": "uuid"}, "digest": object{"type": "string"}, "bytes": object{"type": "integer"}, "graph": ref("Graph")})
	schemas["HistorySource"] = strictObject([]string{"id", "diagramId", "datasetId", "datasetVersion", "rowId", "bytes", "dataset"}, object{"id": object{"type": "string"}, "diagramId": object{"type": "string", "format": "uuid"}, "datasetId": object{"type": "string", "format": "uuid"}, "datasetVersion": object{"type": "integer"}, "rowId": object{"type": "string"}, "bytes": object{"type": "integer"}, "dataset": object{"type": "object", "additionalProperties": true, "description": "Shared source header without rows."}})
	schemas["HistoryRowBackup"] = strictObject([]string{"id", "diagramId", "digest", "bytes"}, object{"id": object{"type": "string"}, "diagramId": object{"type": "string", "format": "uuid"}, "digest": object{"type": "string"}, "bytes": object{"type": "integer"}, "rows": object{"type": "array", "items": object{"type": "array", "items": object{"type": "string"}}}, "datasetRef": strictObject([]string{"id", "version"}, object{"id": object{"type": "string", "format": "uuid"}, "version": object{"type": "integer"}})})
	schemas["HistoryRowBackup"].(object)["description"] = "Exactly one of rows or datasetRef. A dataset reference resolves identical rows already exported in the workspace's datasets array, avoiding duplicate large source data."
	schemas["HistoryRowBackup"].(object)["oneOf"] = []any{object{"required": []string{"rows"}, "not": object{"required": []string{"datasetRef"}}}, object{"required": []string{"datasetRef"}, "not": object{"required": []string{"rows"}}}}
	schemas["HistoryBackup"] = strictObject([]string{"version", "snapshots", "contents", "sources", "rows"}, object{"version": object{"type": "integer", "enum": []int{1}}, "snapshots": object{"type": "array", "maxItems": 1000, "items": ref("HistorySnapshot")}, "contents": object{"type": "array", "items": ref("HistoryContent")}, "sources": object{"type": "array", "items": ref("HistorySource")}, "rows": object{"type": "array", "items": ref("HistoryRowBackup")}})
}
