package main

import "visualnerve/internal/model"

func addSpatialSchemas(schemas object) {
	schemas["SpatialPoint"] = object{"type": "object", "required": []string{"x", "y", "z"}, "additionalProperties": false, "properties": object{"x": object{"type": "number", "minimum": -1000000, "maximum": 1000000}, "y": object{"type": "number", "minimum": -1000000, "maximum": 1000000}, "z": object{"type": "number", "minimum": -1000000, "maximum": 1000000}}}
	schemas["SpatialCameraPoint"] = object{"type": "object", "required": []string{"x", "y", "z"}, "additionalProperties": false, "properties": object{"x": object{"type": "number", "minimum": -10000000, "maximum": 10000000}, "y": object{"type": "number", "minimum": -10000000, "maximum": 10000000}, "z": object{"type": "number", "minimum": -10000000, "maximum": 10000000}}}
	schemas["SpatialCameraUp"] = object{"type": "object", "required": []string{"x", "y", "z"}, "additionalProperties": false, "description": "Unit up vector, not parallel to position-target. Defaults to +Y when omitted. Preserves roll from the Z-axis view control.", "properties": object{"x": object{"type": "number", "minimum": -1, "maximum": 1}, "y": object{"type": "number", "minimum": -1, "maximum": 1}, "z": object{"type": "number", "minimum": -1, "maximum": 1}}}
	schemas["SpatialCamera"] = object{"type": "object", "required": []string{"position", "target"}, "additionalProperties": false, "description": "Position must differ from target. +Y is up, +Z is front and -X is left. Camera coordinates have a wider limit to frame all valid node positions. Optional up preserves view roll.", "properties": object{"position": ref("SpatialCameraPoint"), "target": ref("SpatialCameraPoint"), "up": ref("SpatialCameraUp")}}
	schemas["SpatialView"] = object{"type": "object", "required": []string{"version", "mode"}, "additionalProperties": false, "properties": object{"version": object{"type": "integer", "enum": []int{1}}, "mode": object{"type": "string", "enum": []string{"2d", "3d"}}, "camera": ref("SpatialCamera")}}
	schemas["SpatialNode"] = object{"description": "Optional explicit 3D placement of the same native node. Changing only this position preserves the 2D export layout. Moving displayed 2D geometry shifts existing X/Y using the previous relief scale and preserves Z; explicit new XYZ in the same command takes precedence. Front and back retain the native 2D appearance, with readable unmirrored back text.", "type": "object", "required": []string{"version"}, "additionalProperties": false, "properties": object{"version": object{"type": "integer", "enum": []int{1}}, "position": ref("SpatialPoint")}}
	schemas["SpatialDiagramInput"] = object{"type": "object", "required": []string{"name"}, "additionalProperties": false, "properties": object{"name": object{"type": "string", "minLength": 1, "maxLength": 500}, "type": object{"type": "string", "enum": model.DiagramTypes}}}
}
