package main

func addSqlSchemas(schemas object) {
	schemas["SqlInput"] = object{"type": "object", "required": []string{"sql"}, "additionalProperties": false, "description": "Analyzed locally in a cancellable browser worker, never executed or sent to a database. Decoded UTF-8 script limit is 50 MiB; the bridge JSON request envelope is limited to 32 MiB.", "properties": object{"sql": object{"type": "string", "minLength": 1, "maxLength": 50 * 1024 * 1024}, "name": object{"type": "string", "minLength": 1, "maxLength": 500}}}
	schemas["SqlQueryReference"] = object{"type": "object", "additionalProperties": false, "required": []string{"column", "resolution"}, "properties": object{"scope": object{"type": "string", "maxLength": 100}, "sourceAlias": object{"type": "string", "maxLength": 1000}, "column": object{"type": "string", "minLength": 1, "maxLength": 1000}, "resolution": object{"type": "string", "enum": []string{"resolved", "unresolved", "ambiguous"}}, "correlated": object{"type": "boolean"}}}
	schemas["SqlQueryOutput"] = object{"type": "object", "additionalProperties": false, "required": []string{"ordinal", "name", "expression", "references"}, "properties": object{"ordinal": object{"type": "integer", "minimum": 1, "maximum": 10000}, "name": object{"type": "string", "minLength": 1, "maxLength": 1000}, "alias": object{"type": "string", "maxLength": 1000}, "expression": object{"type": "string", "minLength": 1, "maxLength": 100000}, "references": object{"type": "array", "maxItems": 100000, "items": ref("SqlQueryReference")}, "duplicateAlias": object{"type": "boolean"}}}
	schemas["SqlQueryClauses"] = object{"type": "object", "additionalProperties": false, "properties": object{}}
	for _, clause := range []string{"from", "where", "groupBy", "having", "orderBy", "limit"} {
		schemas["SqlQueryClauses"].(object)["properties"].(object)[clause] = object{"type": "string", "minLength": 1, "maxLength": 100000}
	}
	schemas["SqlQuerySource"] = object{"type": "object", "additionalProperties": false, "required": []string{"version", "scope", "alias", "kind", "qualifiedName", "columns"}, "description": "A scoped table alias, derived table or CTE instance. Columns are observed query references, not an inferred database schema. Non-table sources require queryScope. References use logical scope/alias identities, not node UUIDs.", "properties": object{"version": object{"type": "integer", "enum": []int{1}}, "scope": object{"type": "string", "minLength": 1, "maxLength": 100}, "alias": object{"type": "string", "minLength": 1, "maxLength": 1000}, "kind": object{"type": "string", "enum": []string{"table", "derived", "cte"}}, "qualifiedName": object{"type": "array", "maxItems": 32, "items": object{"type": "string", "maxLength": 1000}}, "columns": object{"type": "array", "maxItems": 100000, "items": object{"type": "string", "maxLength": 1000}}, "queryScope": object{"type": "string", "maxLength": 100}}}
	schemas["SqlQueryResult"] = object{"type": "object", "additionalProperties": false, "required": []string{"version", "scope", "name", "distinct", "columns", "clauses"}, "description": "Ordered output expressions and logical query clauses, including their literal values. No database execution plan or returned rows.", "properties": object{"version": object{"type": "integer", "enum": []int{1}}, "scope": object{"type": "string", "minLength": 1, "maxLength": 100}, "parentScope": object{"type": "string", "maxLength": 100}, "name": object{"type": "string", "minLength": 1, "maxLength": 1000}, "distinct": object{"type": "boolean"}, "columns": object{"type": "array", "minItems": 1, "maxItems": 10000, "items": ref("SqlQueryOutput")}, "clauses": ref("SqlQueryClauses")}}
	schemas["SqlQueryRelationship"] = object{"type": "object", "additionalProperties": false, "required": []string{"version", "scope", "kind"}, "properties": object{"version": object{"type": "integer", "enum": []int{1}}, "scope": object{"type": "string", "minLength": 1, "maxLength": 100}, "kind": object{"type": "string", "enum": []string{"join", "input", "lineage", "subquery"}}, "joinType": object{"type": "string", "maxLength": 100}, "condition": object{"type": "string", "maxLength": 100000}, "references": object{"type": "array", "maxItems": 100000, "items": ref("SqlQueryReference")}, "outputOrdinals": object{"type": "array", "maxItems": 10000, "items": object{"type": "integer", "minimum": 1, "maximum": 10000}}}}
	schemas["SqlImportResult"] = object{"type": "object", "additionalProperties": false, "required": []string{"graph", "warnings", "tableCount", "columnCount", "relationshipCount", "ignoredStatementCount"}, "properties": object{"graph": ref("Graph"), "warnings": object{"type": "array", "maxItems": 100, "items": object{"type": "string"}}, "tableCount": object{"type": "integer", "minimum": 0}, "columnCount": object{"type": "integer", "minimum": 0}, "relationshipCount": object{"type": "integer", "minimum": 0}, "ignoredStatementCount": object{"type": "integer", "minimum": 0}, "kind": object{"type": "string", "enum": []string{"schema", "query"}}, "queryCount": object{"type": "integer", "minimum": 0, "maximum": 100}, "sourceCount": object{"type": "integer", "minimum": 0, "maximum": 2000}, "outputColumnCount": object{"type": "integer", "minimum": 0, "maximum": 10000}}}
}
